
import json
import sys
import os, signal
import time
import psutil

PROCNAME = "chrome"

#input_path = '/Users/sahiljain/Google_Drive/SBU/Academics/Spring_16/CSE534/FCN_Project/git_code_self'
input_path = '~/Desktop/git_code/fcn_project'
input_file = 'websites_10.txt'



def analyze():
    # file = input_path + '/' + input_file
    # f=open(file)

    # Go to Resource directory
    os.chdir('/home/sahil/Desktop/git_code/fcn_project')
    os.system("sudo chmod -R 777 .")
	
    list_100 = ["google.com",
    "youtube.com",
    "facebook.com",
    "baidu.com",
    "yahoo.com",
    "wikipedia.org",
    "amazon.com",
    "qq.com",
    "twitter.com",
    "google.co.in",
    "live.com",
    "taobao.com",
    "bing.com",
    "google.co.jp",
    "msn.com",
    "yahoo.co.jp",
    "sina.com.cn",
    "linkedin.com",
    "weibo.com",
    "vk.com",
    "instagram.com",
    "google.ru",
    "yandex.ru",
    "hao123.com",
    "google.de",
    "ebay.com",
    "reddit.com",
    "google.co.uk",
    "google.com.br",
    "amazon.co.jp",
    "t.co",
    "google.fr",
    "pinterest.com",
    "mail.ru",
    "tmall.com",
    "360.cn",
    "microsoft.com",
    "netflix.com",
    "onclickads.net",
    "google.it",
    "sohu.com",
    "wordpress.com",
    "tumblr.com",
    "google.es",
    "blogspot.com",
    "imgur.com",
    "naver.com",
    "paypal.com",
    "stackoverflow.com",
    "chinadaily.com.cn",
    "xvideos.com",
    "apple.com",
    "google.com.mx",
    "aliexpress.com",
    "gmw.cn",
    "imdb.com",
    "fc2.com",
    "google.co.kr",
    "diply.com",
    "github.com",
    "google.ca",
    "pornhub.com",
    "google.com.hk",
    "amazon.de",
    "office.com",
    "ok.ru",
    "whatsapp.com",
    "google.com.tr",
    "alibaba.com",
    "rakuten.co.jp",
    "jd.com",
    "ask.com",
    "google.co.id",
    "kat.cr",
    "nicovideo.jp",
    "craigslist.org",
    "google.pl",
    "pixnet.net",
    "xinhuanet.com",
    "tianya.cn",
    "soso.com",
    "xhamster.com",
    "blogger.com",
    "googleusercontent.com",
    "amazon.in",
    "go.com",
    "dropbox.com",
    "google.com.au",
    "cntv.cn",
    "amazon.co.uk",
    "bongacams.com",
    "outbrain.com",
    "youku.com",
    "coccoc.com",
    "wikia.com",
    "microsoftonline.com",
    "youth.cn",
    "cnn.com",
    "google.com.tw",
    "163.com"]

    list_200_250 = ["amazon.it",
			"putlocker.is",
			"douyu.com",
			"varzesh3.com",
			"flickr.com",
			"godaddy.com",
			"w3schools.com",
			"github.io",
			"taboola.com",
			"feedly.com",
			"google.com.ng",
			"softonic.com",
			"tripadvisor.com",
			"google.com.pe",
			"google.ro",
			"bp.blogspot.com",
			"ifeng.com",
			"rdsa2012.com",
			"google.be",
			"washingtonpost.com",
			"google.com.sg",
			"tistory.com",
			"thepiratebay.se",
			"youporn.com",
			"livejournal.com",
			"foxnews.com",
			"deviantart.com",
			"ikea.com",
			"udn.com",
			"amazon.fr",
			"hclips.com",
			"wittyfeed.com",
			"homedepot.com",
			"target.com",
			"web.de",
			"forbes.com",
			"mozilla.org",
			"comcast.net",
			"wikihow.com",
			"mega.nz",
			"google.com.ph",
			"leboncoin.fr",
			"orange.fr",
			"google.se",
			"youm7.com",
			"babytree.com",
			"51.la",
			"csdn.net",
			"gmx.net",
			"skype.com",
			"snapdeal.com"];    # 10 iterations

    for line in list_100:
        for i in range(10):
            website = line.strip()
            output_file = website + str(i) + '.txt'
            os.system("/home/sahil/Desktop/Release/chrome "+website+" 2> " + output_file)
            

if __name__ == '__main__':
    analyze()
